### ISSUE TITLE
Add support for InstanceContent endpoint

### ISSUE THREAD

**Issue by ArthanJans** [freyamade/xivapi-cr#6]
The XIVAPI endpoint for InstanceContent is not currently supported as it not mentioned in the xivapi docs page. The endpoint is found at https://xivapi.com/InstanceContent/<id>

**Comment by freyamade** [comment]
This should be generalised into a method that implements [this endpoint](https://xivapi.com/docs/Game-Data#lists)

**Comment by freyamade** [comment]
and [this one](https://xivapi.com/docs/Game-Data#data) since read methods are also good I guess?

These methods would go in `src/client/other.cr` and shouldn't be too hard to implement :eyes:
