### ISSUE TITLE
Clash between docs/XIVAPI/Dataclasses/PvPTeam.html and docs/XIVAPI/Dataclasses/PvpTeam.html

### ISSUE THREAD

**Issue by ArthanJans** [freyamade/xivapi-cr#8]
Either docs/XIVAPI/Dataclasses/PvPTeam.html or docs/XIVAPI/Dataclasses/PvpTeam.html should be removed or renamed to allow compatibility with case insensitive filesystems

**Comment by freyamade** [comment]
why are there two? :thinking:

**Comment by freyamade** [comment]
Okay so I found the issue;

```crystal
# src/dataclasses/pvp_team_response.cr

module XIVAPI
  module Dataclasses
    # Dataclass for the data that comes in a response from reading a specific PvP Team.
    class PvPTeam
```

**Comment by freyamade** [comment]
how the heck did this thing compile when the client method for pvp_team had `PvpTeamResponse` as it's return type? :thinking:
